MIMOSA_XMLNS = "http://www.mimosa.org/osa-eai/v3-2/xml/CCOM-ML"
XSI_XMLNS = "http://www.w3.org/2001/XMLSchema-instance"
POSTBACK_HOST = "localhost"
POSTBACK_PORT = "4567"
POSTBACK_PATH = "/CCOMData/ActualEvent"
POSTBACK_URI = "http://#{POSTBACK_HOST}:#{POSTBACK_PORT}#{POSTBACK_PATH}"
APP_VERSION = "2.7.3"