defaults: &defaults
  host: localhost

development:
  <<: *defaults
  ccom_database: mimosa_dev

test:
  <<: *defaults
  ccom_database: mimosa_test

production:
  <<: *defaults
  ccom_database: mimosa_production