defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: mimosa_dev

test:
  <<: *defaults
  database: mimosa_test

production:
  <<: *defaults
  host: db.mongohq.com
  username: user
  password: pass
  database: fanboy
